- hosts: masters
  become: yes
  gather_facts: false
  tasks: 
   - name: Creating config-map for node-problem-detector
     shell: kubectl create -f /monitoring_manifests/node-problem-detector/node-problem-detector-config.yaml
   - name: Deploy node problem detector daemonset
     shell: kubectl create -f /monitoring_manifests/node-problem-detector/node-problem-detector.yaml
   - name: Creating node-problem-detector service endpoint
     shell: kubectl create -f /monitoring_manifests/node-problem-detector/service.yaml
